name: climate_wise
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.31.1
  firebase_auth: ^4.15.2
  get: ^4.6.6
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  url_launcher: ^6.2.6
  app_links: ^6.1.1
  github_sign_in_plus: ^0.0.2
  lottie: ^3.0.0
  geolocator: ^12.0.0
  http: ^0.13.5
  intl: ^0.19.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  smooth_page_indicator: ^1.1.0
  sqflite: ^2.3.3+1
  image_picker: ^1.1.2
  firebase_storage: ^11.7.6
  firebase_messaging: ^14.9.3
  flutter_local_notifications: ^9.8.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/facebook_logo.png
      - assets/github_logo.png
      - assets/google_logo.png
      - assets/google_logo.jpg
      - assets/email_logo.png
      - assets/user_profile.png
      - assets/animations/logo.json
      - assets/animations/forgot_logo.json
      - assets/animations/verify_logo.json
      - assets/scroll-1.jpg
      - assets/scroll-1.png

  
fonts:
- family: Poppins
  fonts:
    - assets/fonts/Poppins-Black.ttf
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-Light.ttf
    - assets/fonts/Poppins-Medium.ttf
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Thin.ttf

